DELETE FROM PUBLIC.GENRE;
DELETE FROM PUBLIC.FRIENDS_STATUS;
DELETE FROM PUBLIC.FRIENDS;
DELETE FROM PUBLIC.MPA;
DELETE FROM PUBLIC.FILM;
DELETE FROM PUBLIC.FILM_GENRE;
DELETE FROM PUBLIC.FILMS_LIKES;
DELETE FROM PUBLIC.USERS;

INSERT INTO PUBLIC.GENRE (GENRE_ID, GENRE) VALUES  (1,'Комедия');
INSERT INTO PUBLIC.GENRE (GENRE_ID, GENRE) VALUES  (2,'Драма');
INSERT INTO PUBLIC.GENRE (GENRE_ID, GENRE) VALUES  (3,'Мультфильм');
INSERT INTO PUBLIC.GENRE (GENRE_ID, GENRE) VALUES  (4,'Триллер');
INSERT INTO PUBLIC.GENRE (GENRE_ID, GENRE) VALUES  (5,'Документальный');
INSERT INTO PUBLIC.GENRE (GENRE_ID, GENRE) VALUES  (6,'Боевик');

INSERT INTO PUBLIC.MPA (RATING_ID, RATING) VALUES (1,'G');
INSERT INTO PUBLIC.MPA (RATING_ID, RATING) VALUES (2,'PG');
INSERT INTO PUBLIC.MPA (RATING_ID, RATING) VALUES (3,'PG-13');
INSERT INTO PUBLIC.MPA (RATING_ID, RATING) VALUES (4,'R');
INSERT INTO PUBLIC.MPA (RATING_ID, RATING) VALUES (5,'NC-17');

INSERT INTO PUBLIC.FRIENDS_STATUS (STATUS_ID, STATUS) VALUES  (1,'UNCONFIRMED');
INSERT INTO PUBLIC.FRIENDS_STATUS (STATUS_ID, STATUS) VALUES  (2,'CONFIRMED');

